spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/doacoes
    username: asilo
    password: asilo123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

flyway:
  enabled: true

logging:
  level:
    org.springframework: INFO
